security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers: #va définir où on va chercher les utilisateurs
        mon_user_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User: bcrypt
    firewalls: #les firewall vont nous permettre de définir des pages accessibles uniquement aux utilisateurs connectés
        dev: #ne pas toucher celui-ci, il permet juste d'acceder au webprofiler sur toutes les pages
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main: #le firewall sur lequel on va travailler
            anonymous: true  #veut dire que le site est accessible aux utilisateurs non authentifiés
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    # Pour contrôler l'accès  pour une partie du site (par ex zone admin)
    access_control:
        #tout les url commençant par /admin ne seront accessibles que par un user ayant ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    # on définit une hierarchie entre les roles
    role_hierarchy:
            ROLE_AUTEUR:       ROLE_USER  #un user qui a le ROLE_AUTEUR aura aussi le ROLE_USER
            ROLE_ADMIN: [ROLE_AUTEUR, ROLE_MODERATEUR] #un user qui a le ROLE_ADMIN aura aussi le ROLE_AUTEUR et donc le ROLE_USER