#nom de la route
#index:
#    path: /bonjour #le chemin que l'on veut faire correspondre
#    controller: App\Controller\HomeController::bonjour  #le controlleur à appeler : Mon\Namespace\MaClasse::maMethode
